export type Lang = "ar" | "fr";

export const translations: Record<string, { ar: string; fr: string }> = {
  appName: {
    ar: "الملحقة الإدارية 14",
    fr: "Annexe Administrative 14",
  },
  appSubtitle: {
    ar: "أكادير - البوابة الرقمية للخدمات",
    fr: "Agadir - Portail Numérique des Services",
  },
  appTitle: {
    ar: "الملحقة الإدارية 14 - أكادير | البوابة الرقمية للخدمات",
    fr: "Annexe Administrative 14 - Agadir | Portail Numérique",
  },
  appDesc: {
    ar: "البوابة الرقمية للملحقة الإدارية 14 - أكادير - تقديم طلبات الشواهد والشكايات وتتبعها إلكترونيا",
    fr: "Portail numérique de l'Annexe Administrative 14 - Agadir - Demandes de certificats, réclamations et suivi en ligne",
  },
  // Nav
  home: { ar: "الرئيسية", fr: "Accueil" },
  services: { ar: "الخدمات", fr: "Services" },
  trackRequests: { ar: "تتبع الطلبات", fr: "Suivi des demandes" },
  employee: { ar: "موظف", fr: "Employé" },
  employeePortal: { ar: "بوابة الموظف", fr: "Portail Employé" },
  // Hero
  heroBadge: {
    ar: "الملحقة الإدارية 14 - أكادير | البوابة الرقمية الرسمية",
    fr: "Annexe Administrative 14 - Agadir | Portail Officiel",
  },
  heroTitle1: { ar: "مرحبا بكم في", fr: "Bienvenue sur" },
  heroTitle2: { ar: "البوابة الرقمية", fr: "le Portail Numérique" },
  heroTitle3: { ar: "للملحقة الإدارية 14 - أكادير", fr: "de l'Annexe Administrative 14 - Agadir" },
  heroDesc: {
    ar: "منصة إلكترونية لتسهيل الإجراءات الإدارية. تقديم طلبات الشواهد، تتبعها، وتقديم الشكايات بكل يسر وسهولة.",
    fr: "Plateforme électronique pour faciliter les démarches administratives. Demandes de certificats, suivi et réclamations en toute simplicité.",
  },
  startNow: { ar: "ابدأ طلبك الآن", fr: "Commencez maintenant" },
  browseServices: { ar: "استعرض الخدمات", fr: "Voir les services" },
  quickInfo: { ar: "معلومات سريعة", fr: "Informations rapides" },
  employees: { ar: "أعوان السلطة", fr: "Agents d'Autorité" },
  neighborhoods: { ar: "الأحياء", fr: "Quartiers" },
  // Services
  serviceTitle: { ar: "خدماتنا الإلكترونية", fr: "Nos Services en Ligne" },
  serviceSubtitle: { ar: "خدمات رقمية مبتكرة لتوفير الوقت والجهد", fr: "Des services numériques innovants pour vous faciliter la vie" },
  requestCert: { ar: "طلب شهادة", fr: "Demande de certificat" },
  requestCertDesc: { ar: "تقديم طلب للحصول على الشواهد الإدارية", fr: "Soumettre une demande de certificat administratif" },
  complaint: { ar: "تقديم شكاية", fr: "Déposer une réclamation" },
  complaintDesc: { ar: "تقديم شكاية أو تظلم إداري", fr: "Soumettre une réclamation administrative" },
  aawan: { ar: "أعوان السلطة", fr: "Agents d'Autorité" },
  aawanDesc: { ar: "البحث عن عون السلطة المكلف بحيك والتواصل معه", fr: "Rechercher l'agent responsable de votre quartier" },
  trackTitle: { ar: "تتبع الطلب", fr: "Suivi des demandes" },
  trackDesc: { ar: "متابعة حالة طلباتك السابقة", fr: "Suivre l'état de vos demandes" },
  // How it works
  howTitle: { ar: "كيف تعمل الخدمة؟", fr: "Comment ça marche ?" },
  howSubtitle: { ar: "خطوات بسيطة للحصول على خدماتك الإدارية", fr: "Des étapes simples pour vos démarches" },
  step1: { ar: "تسجيل الدخول", fr: "Identification" },
  step1Desc: { ar: "أدخل رقم بطاقتك الوطنية ومعلوماتك الشخصية", fr: "Entrez votre CIN et vos informations" },
  step2: { ar: "اختيار الخدمة", fr: "Choix du service" },
  step2Desc: { ar: "اختر نوع الشهادة التي تريد تقديمها", fr: "Choisissez le type de certificat" },
  step3: { ar: "إرفاق الوثائق", fr: "Documents requis" },
  step3Desc: { ar: "أرفق الوثائق المطلوبة", fr: "Joignez les documents nécessaires" },
  step4: { ar: "التتبع", fr: "Suivi" },
  step4Desc: { ar: "تتبع طلبك في الوقت الفعلي", fr: "Suivez votre demande en temps réel" },
  // Employee CTA
  empCtaTitle: { ar: "بوابة الموظف", fr: "Portail Employé" },
  empCtaDesc: { ar: "تسجيل الدخول إلى الفضاء الخاص بعون السلطة", fr: "Accédez à l'espace agent d'autorité" },
  empLogin: { ar: "دخول الموظفين", fr: "Connexion Employé" },
  // Footer
  footerQuickLinks: { ar: "روابط سريعة", fr: "Liens rapides" },
  footerContact: { ar: "معلومات الاتصال", fr: "Contact" },
  footerPhone: { ar: "الهاتف", fr: "Tél" },
  footerEmail: { ar: "البريد", fr: "Email" },
  footerAddress: { ar: "العنوان: الملحقة الإدارية 14، أكادير", fr: "Adresse: Annexe Administrative 14, Agadir" },
  footerRights: { ar: "جميع الحقوق محفوظة", fr: "Tous droits réservés" },
  // Forms
  fullName: { ar: "الاسم الكامل", fr: "Nom complet" },
  cin: { ar: "رقم البطاقة الوطنية", fr: "N° Carte Nationale" },
  phone: { ar: "رقم الهاتف", fr: "N° Téléphone" },
  address: { ar: "العنوان الكامل", fr: "Adresse complète" },
  neighborhood: { ar: "الحي", fr: "Quartier" },
  selectNeighborhood: { ar: "اختر حيك", fr: "Choisissez votre quartier" },
  certType: { ar: "نوع الشهادة", fr: "Type de certificat" },
  notes: { ar: "ملاحظات إضافية", fr: "Notes supplémentaires" },
  required: { ar: "مطلوب", fr: "Requis" },
  submit: { ar: "تقديم", fr: "Soumettre" },
  cancel: { ar: "إلغاء", fr: "Annuler" },
  confirm: { ar: "تأكيد", fr: "Confirmer" },
  back: { ar: "السابق", fr: "Précédent" },
  next: { ar: "التالي", fr: "Suivant" },
  // Status
  statusMoudakhela: { ar: "موداخلة", fr: "Soumise" },
  statusEtude: { ar: "قيد الدراسة", fr: "En cours d'étude" },
  statusMoulaja: { ar: "مولجة", fr: "Transmise" },
  statusMoamala: { ar: "معاملة", fr: "En traitement" },
  statusMutam: { ar: "متم", fr: "Complétée" },
  statusMamboula: { ar: "مرفوضة", fr: "Refusée" },
  // Employee dashboard
  welcome: { ar: "مرحبا", fr: "Bienvenue" },
  refresh: { ar: "تحديث", fr: "Actualiser" },
  logout: { ar: "خروج", fr: "Déconnexion" },
  total: { ar: "المجموع", fr: "Total" },
  inProgress: { ar: "قيد المعالجة", fr: "En cours" },
  completed: { ar: "مكتملة", fr: "Complétées" },
  rejected: { ar: "مرفوضة", fr: "Refusées" },
  allRequests: { ar: "جميع الطلبات", fr: "Toutes les demandes" },
  allStatus: { ar: "جميع الحالات", fr: "Tous les statuts" },
  noRequests: { ar: "لا توجد طلبات", fr: "Aucune demande" },
  noRequestsDesc: { ar: "لا توجد طلبات جديدة في حيك", fr: "Aucune demande dans votre secteur" },
  // Request page
  requestCertTitle: { ar: "طلب شهادة", fr: "Demande de certificat" },
  formRequestCertDesc: { ar: "املأ المعلومات التالية لتقديم طلب الحصول على شهادة إدارية", fr: "Remplissez le formulaire pour demander un certificat" },
  stepInfo: { ar: "معلومات شخصية", fr: "Informations personnelles" },
  stepDocs: { ar: "إرفاق الوثائق", fr: "Documents" },
  stepConfirm: { ar: "تأكيد الطلب", fr: "Confirmation" },
  uploadDocs: { ar: "يرجى إرفاق الوثائق المطلوبة", fr: "Veuillez joindre les documents requis" },
  acceptedFormats: { ar: "الصيغ المقبولة: JPG, PNG, PDF", fr: "Formats acceptés: JPG, PNG, PDF" },
  cinCard: { ar: "البطاقة الوطنية", fr: "Carte Nationale" },
  electricityBill: { ar: "فاتورة الكهرباء", fr: "Facture d'électricité" },
  witnessCert: { ar: "شهادة الشهود (إن وجد)", fr: "Attestation de témoins (si nécessaire)" },
  otherDoc: { ar: "وثيقة أخرى", fr: "Autre document" },
  camera: { ar: "تصوير بالكاميرا", fr: "Photo avec caméra" },
  successTitle: { ar: "تم تقديم طلبك بنجاح!", fr: "Votre demande a été soumise avec succès!" },
  successDesc: { ar: "سيتم معالجة طلبك من طرف عون السلطة المختص", fr: "Votre demande sera traitée par l'agent d'autorité compétent" },
  newRequest: { ar: "طلب جديد", fr: "Nouvelle demande" },
  // Complaint
  complaintTitle: { ar: "تقديم شكاية", fr: "Déposer une réclamation" },
  formComplaintDesc: { ar: "تقديم شكاية أو تظلم إداري إلى عون السلطة المختص", fr: "Soumettre une réclamation à l'agent d'autorité" },
  subject: { ar: "موضوع الشكاية", fr: "Sujet de la réclamation" },
  complaintDetails: { ar: "شرح الشكاية", fr: "Détails de la réclamation" },
  attachDocs: { ar: "إرفاق وثائق داعمة", fr: "Joindre des documents" },
  complaintSuccess: { ar: "تم تقديم شكايتك بنجاح!", fr: "Votre réclamation a été soumise avec succès!" },
  // Track
  trackPageTitle: { ar: "تتبع الطلبات", fr: "Suivi des demandes" },
  trackPageDesc: { ar: "أدخل رقم بطاقتك الوطنية لتتبع طلباتك السابقة", fr: "Entrez votre CIN pour suivre vos demandes" },
  search: { ar: "بحث", fr: "Rechercher" },
  noResults: { ar: "لا توجد طلبات", fr: "Aucune demande trouvée" },
  noResultsDesc: { ar: "لم يتم العثور على أي طلبات بهذا الرقم", fr: "Aucune demande trouvée avec ce numéro" },
  // Employee login
  empLoginTitle: { ar: "بوابة الموظف", fr: "Portail Employé" },
  empLoginDesc: { ar: "تسجيل الدخول إلى فضاء عون السلطة", fr: "Connexion à l'espace agent" },
  email: { ar: "البريد الإلكتروني", fr: "Email" },
  password: { ar: "كلمة المرور", fr: "Mot de passe" },
  login: { ar: "تسجيل الدخول", fr: "Connexion" },
  demoCredentials: { ar: "بيانات تسجيل الدخول التجريبية:", fr: "Identifiants de démonstration:" },
  // Info messages
  infoMsg: { ar: "كل طلب يوجه تلقائيا إلى عون السلطة المختص بالحي الذي تنتمي إليه. تأكد من إدخال عنوانك السكني بشكل صحيح.", fr: "Chaque demande est automatiquement transmise à l'agent d'autorité de votre quartier." },
  // About page - nav
  about: { ar: "حول الملحقة", fr: "À propos" },
  aboutTitle: { ar: "حول الملحقة الإدارية 14", fr: "À propos de l'Annexe Administrative 14" },
  aboutSubtitle: { ar: "معلومات شاملة حول مهام وخدمات الملحقة الإدارية 14 بأكادير", fr: "Informations complètes sur les missions et services de l'Annexe Administrative 14 d'Agadir" },
  article1Title: { ar: "التعريف بالملحقة الإدارية 14", fr: "Présentation de l'Annexe Administrative 14" },
  article1Content: { ar: "الملحقة الإدارية 14 هي إحدى الملحقات الإدارية التابعة لعمالة أكادير إداوتنان، وتعمل تحت إشراف السلطة المحلية (قائد المقاطعة). تهدف الملحقة إلى تقريب الإدارة من المواطنين وتيسير الحصول على الخدمات الإدارية الأساسية. تشرف الملحقة على ستة أحياء رئيسية: حي الداخلة، حي الداخلة 2 (F1-F20)، حي القدس، حي الفضية، حي الوفاء، والمختار السوسي. تعمل الملحقة على مدار الأسبوع من الإثنين إلى الجمعة، وتستقبل المواطنين من الساعة 8:30 صباحاً إلى 4:30 مساءً.", fr: "L'Annexe Administrative 14 est l'une des annexes administratives relevant de la Préfecture d'Agadir Ida-Ou-Tanane, fonctionnant sous la supervision de l'autorité locale (Caïd de l'arrondissement). Elle vise à rapprocher l'administration des citoyens et à faciliter l'accès aux services administratifs de base. L'annexe couvre six quartiers principaux: Hay Al Dakhla, Hay Al Dakhla 2 (F1-F20), Hay Al Qods, Hay Al Fiddia, Hay Al Wafaa, et Al Mokhtar Al Soussi. Elle est ouverte du lundi au vendredi, de 8h30 à 16h30." },
  article2Title: { ar: "دور عون السلطة (المقدم)", fr: "Rôle de l'Agent d'Autorité (Moqaddem)" },
  article2Content: { ar: "عون السلطة، المعروف أيضاً ب\"المقدم\"، هو حلقة الوصل بين الإدارة المحلية والمواطنين. يقوم بعدة مهام منها: معاينة الحالة المدنية للسكان، تحرير محاضر معاينة السكنى، متابعة ملفات طلبات الشهادات الإدارية، التبليغ عن المخالفات والقضايا الأمنية، المشاركة في عمليات الإحصاء، المساعدة في تنظيم الانتخابات، والسهر على تطبيق القوانين والأنظمة المحلية. كل عون سلطة مكلف بحي أو مجموعة أحياء محددة، ويمكن للمواطنين التواصل معه مباشرة.", fr: "L'Agent d'Autorité, également connu sous le nom de 'Moqaddem', est le lien entre l'administration locale et les citoyens. Ses missions incluent: le suivi de l'état civil des habitants, la rédaction de procès-verbaux de constatation de résidence, le suivi des dossiers de demande de certificats administratifs, le signalement des infractions, la participation aux opérations de recensement, l'aide à l'organisation des élections, et la veille à l'application des lois. Chaque agent est responsable d'un ou plusieurs quartiers spécifiques." },
  article3Title: { ar: "شهادات السكنى وعدم العمل", fr: "Certificats de Résidence et de Non-Travail" },
  article3Content: { ar: "تقدم الملحقة الإدارية 14 نوعين رئيسيين من الشهادات: شهادة السكنى (شهادة الإقامة) التي تثبت أن المطلوب يسكن بالفعل في العنوان المصرح به بعد معاينة ميدانية من طرف عون السلطة، وشهادة عدم العمل التي تثبت أن المطلوب ليس له عمل أو مصدر دخل ثابت. هاتان الشهادتان مطلوبتان بشكل متكرر للتقديم على المساعدات الاجتماعية، برامج الدعم، التسجيل في التغطية الصحية، أو للاستفادة من برامج السكن الاجتماعي. يمكن تقديم الطلب إلكترونياً عبر هذه البوابة أو حضورياً بمقر الملحقة.", fr: "L'Annexe Administrative 14 propose deux types principaux de certificats: le certificat de résidence qui atteste qu'une personne habite à l'adresse déclarée après constatation sur place par l'agent d'autorité, et le certificat de non-travail qui atteste que la personne n'a pas d'emploi ou de revenu fixe. Ces deux certificats sont fréquemment demandés pour les aides sociales, les programmes de soutien, l'inscription à la couverture médicale, ou les programmes de logement social. La demande peut être soumise en ligne via ce portail ou en personne à l'annexe." },
  article4Title: { ar: "خدمات الحالة المدنية", fr: "Services de l'État Civil" },
  article4Content: { ar: "تسهر الملحقة الإدارية على متابعة ومراقبة الحالة المدنية للسكان في نطاقها الترابي. من بين الخدمات المقدمة: تسجيل المواليد الجدد ووفق الآجال القانونية، معالجة طلبات نسخ من سجلات الحالة المدنية، التصديق على الإمضاءات والوثائق، متابعة تغيير العنوان والسكن، وتسليم شهادات الحياة والإقامة. تتعاون الملحقة مع الدوائر القضائية والمستشفيات والمؤسسات التعليمية لضمان دقة بيانات الحالة المدنية.", fr: "L'Annexe Administrative assure le suivi et le contrôle de l'état civil des habitants de son ressort territorial. Parmi les services proposés: l'enregistrement des nouveau-nés dans les délais légaux, le traitement des demandes de copies des registres d'état civil, la légalisation de signatures et de documents, le suivi des changements d'adresse, et la délivrance d'attestations de vie et de résidence. Elle collabore avec les tribunaux, hôpitaux et établissements scolaires." },
  article5Title: { ar: "التخطيط الحضري وتراخيص البناء", fr: "Urbanisme et Permis de Construire" },
  article5Content: { ar: "تلعب الملحقة الإدارية دوراً هاماً في مجال التخطيط الحضري والتعمير. تقوم بمعاينة المخالفات المتعلقة بالبناء غير المرخص، التعدي على الملك العام، والبناء في المناطق غير القابلة للبناء. تتعاون الملحقة مع المصالح التقنية للجماعة والمكتب الوطني للسلامة الصحية للمنتجات الغذائية (ONSSA) فيما يخص تراخيص البناء. كما تساهم في تطبيق قانون التعمير رقم 12-90 ومتابعة مخالفات التجزئة السكنية غير القانونية.", fr: "L'Annexe Administrative joue un rôle important dans le domaine de l'urbanisme et de l'aménagement. Elle constate les infractions liées aux constructions non autorisées, l'empiètement sur le domaine public et la construction en zones non constructibles. Elle collabore avec les services techniques de la commune et l'ONSSA concernant les permis de construire. Elle contribue également à l'application de la loi 12-90 sur l'urbanisme." },
  article6Title: { ar: "محاربة السكن غير اللائق", fr: "Lutte contre l'Habitat Insalubre" },
  article6Content: { ar: "تولي الملحقة الإدارية أهمية كبيرة لمحاربة السكن غير اللائق والبناء العشوائي. تقوم الفرق الميدانية بمعاينة الأحياء المتضررة، تحرير محاضر حول الحالة الصحية للمساكن، متابعة طلبات الاستفادة من برامج إعادة الإسكان والتأهيل الحضري، والتنسيق مع برنامج \"مدن بدون صفيح\". يمكن للمواطنين تقديم شكايات حول السكن غير اللائق عبر البوابة الرقمية ليتم معالجتها من قبل عون السلطة المختص.", fr: "L'Annexe Administrative accorde une grande importance à la lutte contre l'habitat insalubre et les constructions anarchiques. Les équipes de terrain constatent l'état des quartiers, rédigent des procès-verbaux sur les conditions sanitaires, suivent les demandes de relogement et de réhabilitation urbaine, et coordonnent avec le programme 'Villes Sans Bidonvilles'. Les citoyens peuvent soumettre des réclamations en ligne." },
  article8Title: { ar: "التسجيل في اللوائح الانتخابية", fr: "Inscription sur les Listes Électorales" },
  article8Content: { ar: "تقوم الملحقة الإدارية بدور أساسي في تنظيم العمليات الانتخابية. تشرف على عملية تسجيل الناخبين في اللوائح الانتخابية العامة، تحديث المعلومات الشخصية للناخبين، معالجة طلبات الاعتراض والنقل، وتسليم بطائق التسجيل الانتخابية. كما تشارك في تنظيم مكاتب التصويت يوم الاقتراع وتضمن سير العملية الانتخابية في أحسن الظروف. يمكن للمواطنين الاستعلام عن تسجيلهم الانتخابي بمقر الملحقة.", fr: "L'Annexe Administrative joue un rôle essentiel dans l'organisation des opérations électorales. Elle supervise l'inscription des électeurs sur les listes électorales générales, la mise à jour des informations personnelles, le traitement des demandes de contestation et de transfert, et la délivrance des cartes d'inscription. Elle participe également à l'organisation des bureaux de vote le jour du scrutin." },
  article9Title: { ar: "التوعية البيئية والنظافة", fr: "Sensibilisation à l'Environnement et Propreté" },
  article9Content: { ar: "تعمل الملحقة الإدارية بالتنسيق مع مصالح الجماعة والمجتمع المدني على تحسين الوضع البيئي بالأحياء التابعة لها. من بين الأنشطة: حملات التحسيس بأهمية النظافة وفرز النفايات، مراقبة النقاط السوداء لرمي النفايات، تحرير مخالفات في حق المخالفين لقوانين النظافة، التنسيق مع شركات جمع النفايات، والمشاركة في الحملات الوطنية للنظافة. كما تستقبل الملحقة شكايات المواطنين حول مشاكل النظافة والحشرات والحيوانات الضالة.", fr: "L'Annexe Administrative travaille en coordination avec les services communaux et la société civile pour améliorer la situation environnementale des quartiers. Activités: campagnes de sensibilisation au tri des déchets, surveillance des décharges sauvages, verbalisation des contrevenants, coordination avec les sociétés de collecte, et participation aux campagnes nationales de nettoyage. Elle reçoit également les réclamations sur les problèmes de propreté." },
  article10Title: { ar: "الخدمات الرقمية والحكومة الإلكترونية", fr: "Services Numériques et E-Administration" },
  article10Content: { ar: "في إطار استراتيجية المغرب الرقمي، تقدم الملحقة الإدارية 14 خدماتها الإلكترونية عبر هذه البوابة الرقمية. يمكن للمواطنين تقديم طلبات الشهادات الإدارية إلكترونياً، تتبع حالة طلباتهم في الوقت الفعلي، تقديم الشكايات والتظلمات، والتواصل مع أعوان السلطة مباشرة. تهدف هذه الخدمات إلى تقليل وقت الانتظار، تبسيط المساطر الإدارية، وتحسين جودة الخدمات المقدمة للمواطنين. يتم تحديث البوابة باستمرار لإضافة خدمات جديدة.", fr: "Dans le cadre de la stratégie Maroc Numérique, l'Annexe Administrative 14 propose ses services en ligne via ce portail numérique. Les citoyens peuvent soumettre leurs demandes de certificats en ligne, suivre l'état de leurs demandes en temps réel, déposer des réclamations, et communiquer directement avec les agents d'autorité. Ces services visent à réduire les délais d'attente, simplifier les procédures et améliorer la qualité des services." },
};
